### PR TITLE
changed website logo

### PR DESCRIPTION
**Pull request by abhayksahu369**

### CODE REVIEW

**Comment by Anu27n** [comment]
change the title of page to 603 CoWorkingSpace.

**Comment by abhayksahu369** [comment]
@ okay

**Comment by abhayksahu369** [comment]
@Anu27n  done brother .  
Yesterday's contribution is still not showing in gssoc profile ...i think because you didn't add level tag earlier .... so I didn't get any points.....can you add a level 2 tag here so that I can get some extra points .... if you don't want it's fine

**Comment by Anu27n** [comment]
@abhayksahu369  assugned u pr you can add the labels

**Pull request closed without merging**
