### PR TITLE
"Book a Space" button redirects to new page now

### PR DESCRIPTION
**Pull request by Dhruv-Davda**
I have redirected the "Book A Space" button to the new page successfully. Earlier it was redirecting to home page itself as discussed in the issue i had created. I am attaching the screen-record below aswell. Thankyou !

https://github.com/user-attachments/assets/5b1ae49d-5e62-472e-9166-fb7fe1c86483

### CODE REVIEW

**Comment by Dhruv-Davda** [comment]
@Anu27n please check this out, successfully done. Thanks !

**Comment by Anu27n** [comment]
@Dhruv-Davda actually it should come in make your space not book your space

**Comment by Dhruv-Davda** [comment]
Okay let me do the changes, Thanks for clarifying.

**Comment by Dhruv-Davda** [comment]
@Anu27n Done, could you please check if everything's alright this time ? If not, feel free to ask me to do the further changes. Thanks.

**Comment by Anu27n** [comment]
@Dhruv-Davda  I cant merge as branch as conflicts vreate a new pR

**Pull request closed without merging**
